ALTER TABLE "Book" ADD COLUMN "totalCopies" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Book" ADD COLUMN "isArchived" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Book" ADD COLUMN "archivedAt" DATETIME;
ALTER TABLE "Book" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX "Book_isArchived_idx" ON "Book"("isArchived");
